name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Build Linux
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and export
      run: |
        docker build -f Dockerfile.linux_amd64 -t ${{ secrets.DOCKERHUB_USER }}/anp-demo-app:latest-amd64 .
        docker build -f Dockerfile.linux_amd64 --platform=linux/arm64 -t ${{ secrets.DOCKERHUB_USER }}/anp-demo-app:latest-arm64 .
        
    - uses: actions/checkout@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push images
      run: |
        docker push ${{ secrets.DOCKERHUB_USER }}/anp-demo-app:latest-amd64
        docker push ${{ secrets.DOCKERHUB_USER }}/anp-demo-app:latest-arm64

        docker manifest create \
        ${{ secrets.DOCKERHUB_USER }}/anp-demo-app:latest \
        --amend ${{ secrets.DOCKERHUB_USER }}/anp-demo-app:latest-amd64 \
        --amend ${{ secrets.DOCKERHUB_USER }}/anp-demo-app:latest-arm64

        docker manifest push ${{ secrets.DOCKERHUB_USER }}/anp-demo-app:latest

  build-win1809:
    runs-on: windows-latest
    steps:
    - name: Build Windows 1809
      uses: actions/checkout@v3
    - name: Build and export
      run: |
        docker build -f Dockerfile.win_amd64 --build-arg=KERNEL_VERSION=1809 -t ${{ secrets.DOCKERHUB_USER }}/anp-demo-app:latest-1809 .
    - uses: actions/checkout@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push images
      run: |
        docker push ${{ secrets.DOCKERHUB_USER }}/anp-demo-app:latest-1809

  build-win20H2:
    runs-on: windows-latest
    steps:
    - name: Build Windows 20H2
      uses: actions/checkout@v3
    - name: Build and export
      run: |
        docker build -f Dockerfile.win_amd64 --build-arg=KERNEL_VERSION=20H2 -t ${{ secrets.DOCKERHUB_USER }}/anp-demo-app:latest-20H2 .
    - uses: actions/checkout@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push images
      run: |
        docker push ${{ secrets.DOCKERHUB_USER }}/anp-demo-app:latest-20H2
        
  build-ltsc2022:
    runs-on: windows-latest
    steps:
    - name: Build Windows ltsc2022
      uses: actions/checkout@v3
    - name: Build and export
      run: |
        docker build -f Dockerfile.win_amd64 --build-arg=KERNEL_VERSION=ltsc2022 -t ${{ secrets.DOCKERHUB_USER }}/anp-demo-app:latest-ltsc2022 .
    - uses: actions/checkout@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push images
      run: |
        docker push ${{ secrets.DOCKERHUB_USER }}/anp-demo-app:latest-ltsc2022

